services:
  homeassistant:
    image: homeassistant/home-assistant
    env_file: .env
    ports:
      - "8123:8123"
    volumes:
      - "${HOMEASSISTANT_CONFIG}:/config"
  immich:
    image: immich/immich-server
    env_file: .env
    ports:
      - "${IMMICH_PORT}:2283"
    volumes:
      - "${IMMICH_FOTKY}:/usr/src/app/upload"
